### ISSUE TITLE
Camera speed when mouse hits the screen boundary doesnt work anymore on exagear with XEGW

### ISSUE THREAD

**Issue by jurises99** [ewt45/EDPatch#3]
![Screenshot_2023-06-18-16-03-19-032_com ludashi benchmark](https://github.com/ewt45/EDPatch/assets/22735064/d69baeed-44e1-421d-b65a-7b14ddb17437)

when approaching a boundary while using Exagear XEGW with DRI support for DXVK, the mouse comes to a halt and is unable to move beyond the boundary.

also is it possible if you add a function to re apply patch, cause like if I apply 0.0.2 patch on my exagear, and downloaded 0.0.3 patch, the latest cannot be patched anymore

Tested games:
Skyrim
kingdoms of amalur
oblivion

**Comment by ewt45** [comment]
thanks for reporting. I can't seem to find a solution to the mouse movement. It used to set the limiation of pointer locations out of boundary a little bit, but now it don't have the control of it anymore (xegw takes the control). Though if xegw export the pointer locations in the future, there's posibility to solve this problem with mousewarpoverride registry. Input bridge is the practical solution.
as to the re apply patch function, it's implemented in the recent versions of edpatch.
