### ISSUE TITLE
记事本能输入文字，游戏里无法输入文字

### ISSUE THREAD

**Issue by ColaMint** [ewt45/EDPatch#4]
补补大佬看看能不能帮忙修修这个bug

我试了国内外大佬打包的apk，【貌似】所有【开始集成X11，DXVK不再需要单独启动X11】的apk都会让冒险岛无法输入文字，但是系统自带的记事本是能输入文字的。

国外的网友说在别的游戏好像也有类似的问题

![image](https://github.com/ewt45/EDPatch/assets/12627184/745ea173-9e41-44c1-a16a-9889544e8165)

首先能确定跟渲染模式无关，跟机型无关，但是不知道跟android版本是否有关
我试了家里的所有设备都有这个问题：
Xiaomi 12S Pro - 安卓13
PIxel 3XL - 安卓 11
华为平板 - 鸿蒙3.0

以J大的包为例，从f55版本开始有这个问题

![image](https://github.com/ewt45/EDPatch/assets/12627184/1310f1db-8820-42c8-9faa-244cb1c2f6e5)

还有也能确定跟obb无关，我用J大f54的apk和f55的obb结合使用没有这个问题，所以我判断是apk自身的问题

用f55的演示视频:

https://github.com/ewt45/EDPatch/assets/12627184/c7f81c68-f4a6-4e4b-acdc-bf5c100bf422

**Comment by ewt45** [comment]
apk问题。x11服务器端采用了xegw的，均存在文字输入bug，目前无法解决。
xegw为早期termux-x11，需等待xegw更新

**Comment by ColaMint** [comment]
> apk问题。x11服务器端采用了xegw的，均存在文字输入bug，目前无法解决。 xegw为早期termux-x11的移植，需等待xegw更新

好的谢谢大佬

**Comment by ColaMint** [comment]
> xegw



> apk问题。x11服务器端采用了xegw的，均存在文字输入bug，目前无法解决。 xegw为早期termux-x11的移植，需等待xegw更新

请教一下。我试了一下用官方最新版的 [termux-app](https://github.com/termux/termux-app) 和 [termux-x11](https://github.com/termux/termux-x11)，安装 [termux-box](https://github.com/olegos2/termux-box) 来运行游戏（完全不用ExaGear），也是有同样的问题，能够说明官方最新版的termux-x11本身还是有bug是吗？

**Comment by ewt45** [comment]
termux-x11的preference里，开启  prefer scancodes when possible 再试试呢？
termux-x11现在优先输入unicode字符，如果游戏不是unicode编码的可能读取不了输入（之前在一些老的繁体游戏上出现过这种情况，可能用的是BIG5编码）。

xegw之前，exagear用的是它自己写的x11 server

**Comment by ColaMint** [comment]
> termux-x11的preference里，开启 prefer scancodes when possible 再试试呢？ termux-x11现在优先输入unicode字符，如果游戏不是unicode编码的可能读取不了输入（之前在一些老的繁体游戏上出现过这种情况，可能用的是BIG5编码）。
> 
> xegw之前，exagear用的是它自己写的x11 server

最后发现问题是游戏窗口没有获得焦点（不知道为什么会这样，明明游戏中的光标能在账号和密码间切换）

通过`xdotool windowfocus <windows-id>`让窗口获得焦点后就能正常输入文字了

大佬有空的话也可以考虑做一个patch：

增加一个按钮，通过`xwininfo --tree -root`列举出所有窗口信息

然后用户点击窗口的名字就自动用`xdotool windowfocus <windows-id>`让该窗口获得焦点

**Comment by ewt45** [comment]
> > termux-x11的preference里，开启 prefer scancodes when possible 再试试呢？ termux-x11现在优先输入unicode字符，如果游戏不是unicode编码的可能读取不了输入（之前在一些老的繁体游戏上出现过这种情况，可能用的是BIG5编码）。
> > xegw之前，exagear用的是它自己写的x11 server
> 
> 最后发现问题是游戏窗口没有获得焦点（不知道为什么会这样，明明游戏中的光标能在账号和密码间切换）
> 
> 通过`xdotool windowfocus <windows-id>`让窗口获得焦点后就能正常输入文字了
> 
> 大佬有空的话也可以考虑做一个patch：
> 
> 增加一个按钮，通过`xwininfo --tree -root`列举出所有窗口信息
> 
> 然后用户点击窗口的名字就自动用`xdotool windowfocus <windows-id>`让该窗口获得焦点

这么一说好像也见到过这种事情，全屏无法输入，改成窗口化就可以了，也许也是这个问题。
至于patch的话，linux我不是很熟悉，就先不搞了。祝你游戏愉快=-=
