### ISSUE TITLE
Xegw for ED5in1

### ISSUE THREAD

**Issue by iu333** [ewt45/EDPatch#6]
I would like to ask you to make a function in EDPatch that adds Xegw to older versions of Hugo ED5in1. I tried to add it myself according to your instructions, but it doesn’t work.

**Comment by ewt45** [comment]
try xegw2.2 patcher. it should fix the problem of crashing of hugo versions

**Comment by iu333** [comment]
I used xegw2.2, but hugo.apk gives an error when building. I can't figure out what the reason is.

**Comment by ewt45** [comment]
another person add xegw to hugo 5in1 successfully earlier.
i'm not sure why, does it show any error logs?

**Comment by iu333** [comment]
[ED5in1update.zip](https://github.com/ewt45/EDPatch/files/12608047/ED5in1update.zip)

**Comment by iu333** [comment]
can you try this with this .apk?
[ED5in1update.zip](https://github.com/ewt45/EDPatch/files/12608073/ED5in1update.zip)

**Comment by ewt45** [comment]
there's no errors in logs. when clicking tfm shortcut it crashes and turns back to desktop tab.
but you didn't seem to modify the apk. there's no com.termux.x11.* in dex, and no libxlorie.so

**Comment by iu333** [comment]
Yes, I did not modify this .APK, but I tried to change it and did not work. Therefore, I ask you to try to do it. If this does not complicate you, or please add this function to EDPatch if possible.

**Comment by ewt45** [comment]
sorry i can't do it for you. you can upload a modified apk so that i can check if you edited some thing wrong, or it's patcher's problem.
edpatch can't achieve this for now because it doesn't have the ability to modify xml

**Comment by iu333** [comment]
I see, thanks for the answer, I’ll continue to suffer.

**Comment by iu333** [comment]
Here I put it together, everything seems to be working, but TFM.exe does not start. I can't find what the problem is. Please see if you can give me any advice?
[ED5in1[modv8].zip](https://github.com/ewt45/EDPatch/files/12610834/ED5in1.modv8.zip)

**Comment by iu333** [comment]
Thank you very much for the information, everything works, but the FPS is low. I'll try something else, maybe I can increase the FPS. 👍
